CREATE SMALLFILE TABLESPACE DEMO_TBS
  DATAFILE
  'c:/tbs/demo.dbf' SIZE 136870912 AUTOEXTEND ON NEXT 1 MAXSIZE UNLIMITED
  LOGGING
  DEFAULT
  NOCOMPRESS
  ONLINE
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  SEGMENT SPACE MANAGEMENT MANUAL;
  
CREATE USER DEMO IDENTIFIED BY "1234567890" DEFAULT TABLESPACE DEMO_TBS ACCOUNT UNLOCK;  

GRANT "CONNECT" TO DEMO;
GRANT "RESOURCE" TO DEMO;

--alter user pip2 default role all

ALTER USER DEMO QUOTA UNLIMITED ON DEMO_TBS;

GRANT UNLIMITED TABLESPACE TO DEMO ;


  CREATE TABLE "DEMO"."X_ORDER" 
   (    "ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "ORDER_NAME" NVARCHAR2(32) NOT NULL ENABLE, 
    "ORDER_PRICE" NUMBER(*,0) NOT NULL ENABLE, 
    "ORDER_TIME" DATE NOT NULL ENABLE, 
    "BUYER_ID" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "X_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_TBS" ;
  
    CREATE TABLE "DEMO"."X_USER" 
   (    "USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "USER_NAME" NVARCHAR2(32) NOT NULL ENABLE, 
    "USER_MOBILE" CHAR(11 BYTE) NOT NULL ENABLE, 
    "USER_PWD" NVARCHAR2(32) NOT NULL ENABLE, 
     CONSTRAINT "X_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_TBS" ;

   COMMENT ON COLUMN "DEMO"."X_USER"."USER_MOBILE" IS 'Use mobile as login account';
   
Insert into DEMO.X_USER (USER_ID,USER_NAME,USER_MOBILE,USER_PWD) values (1,'小黑','13333333333','123456');
Insert into DEMO.X_USER (USER_ID,USER_NAME,USER_MOBILE,USER_PWD) values (2,'小白','18888888888','123456');

Insert into DEMO.X_ORDER (ORDER_ID,ORDER_NAME,ORDER_PRICE,ORDER_TIME,BUYER_ID) values (1,'苹果特价',10000,to_date('27-2月 -17','DD-MON-RR'),1);
Insert into DEMO.X_ORDER (ORDER_ID,ORDER_NAME,ORDER_PRICE,ORDER_TIME,BUYER_ID) values (2,'手机特价',9999,to_date('27-2月 -17','DD-MON-RR'),2);




